[global]
# Streamlit configuration for ConsultingAI

# Development settings
developmentMode = false
logLevel = "info"

# Server settings
port = 8501
headless = false
runOnSave = true
fileWatcherType = "auto"

# Browser settings
serverAddress = "localhost"
baseUrlPath = ""
enableCORS = false

# Theme settings
[theme]
primaryColor = "#3b82f6"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8fafc"
textColor = "#1f2937"
font = "sans serif"

# UI settings
[ui]
hideTopBar = false
hideSidebarNav = false

# Client settings
[client]
caching = true
displayEnabled = true
showErrorDetails = true

# Logger settings
[logger]
level = "info"
messageFormat = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"